#! /bin/bash

alias vi=vim
alias top='top -o cpu'
alias ctags=/usr/local/bin/ctags
alias rspec=fast_rspec
alias g=git
alias gc='git commit'
alias ga='git add'
alias gst='git status'
alias iphone='open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app/'
alias emacs='open -na Emacs'

# ruby management
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
if [ -d "$HOME/.rbenv" ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# Rails
function rails_command {
  local cmd=$1
  shift
  if [ -e script/rails ]; then
    script/rails $cmd "$@"
  else
    script/$cmd "$@"
  fi
}
alias ss='rails_command server'
alias sc='rails_command console'

if [ "$BASH_VERSINFO" -ge 4 ]; then
  # bash configurations
  export HISTCONTROL=ignoredups:erasedups
  export HISTSIZE=100000
  export HISTFILESIZE=100000
  export HISTIGNORE="*production*"
  shopt -s histappend
  shopt -s autocd
  shopt -s globstar
  shopt -s checkhash

  #readline
  bind 'set completion-ignore-case on'
  bind 'set skip-completed-text on'
  bind 'set show-all-if-ambiguous on'
  bind 'set mark-symlinked-directories on'
  bind 'set mark-directories on'

  # OSX Specific
  if [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
  fi
  export BUNDLER_EDITOR=sublime
  export LC_CTYPE=en_US
  
  PS1='[\h \W$(__git_ps1 " (%s)")]Ω '
  
  if [ -d ~/.bash-completion.d ]; then
    for f in ~/.bash-completion.d/*.{sh,bash}; do source "$f"; done
  fi
fi

# final path setting
export PATH="./bin:~/bin:~/.bin:/usr/local/bin:$PATH"
