#! /bin/bash

# remove me
PATH="$PATH:/usr/local/bin"

alias vi=vim
alias top='top -o cpu'
alias ctags=/usr/local/bin/ctags
function commit() { git add . && git commit -a "$@" && rake; }
function push() { commit "$@" && git push; }

# ruby management
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
if [ -d "$HOME/.rbenv" ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# Rails
function rails_command {
  local cmd=$1
  shift
  if [ -e script/rails ]; then
    script/rails $cmd "$@"
  else
    script/$cmd "$@"
  fi
}
alias ss='rails_command server'
alias sc='rails_command console'

# bash configurations
export HISTCONTROL=ignoredups:erasedups 
export HISTSIZE=100000
export HISTFILESIZE=100000
shopt -s histappend
shopt -s autocd
shopt -s globstar
shopt -s checkhash

#readline
bind 'set completion-ignore-case on'
bind 'set skip-completed-text on'
bind 'set show-all-if-ambiguous on'
bind 'set mark-symlinked-directories on'
bind 'set mark-directories on'

# OSX Specific
if [ -f /usr/local/etc/bash_completion ]; then
  . /usr/local/etc/bash_completion
fi
if [ -f /Applications/MacVim.app/Contents/MacOS/Vim ]; then
  alias vim=/Applications/MacVim.app/Contents/MacOS/Vim
  alias mvim='vim -g'
  export EDITOR=/Applications/MacVim.app/Contents/MacOS/Vim
fi
export LC_CTYPE=en_US

# Oracle on my mac stuff
export ORACLE_PATH=~/workspace/oracle-32/instantclient_10_2
export DYLD_LIBRARY_PATH=$ORACLE_PATH:$DYLD_LIBRARY_PATH
export SQLPATH=$ORACLE_PATH
export TNS_ADMIN=$ORACLE_PATH

# final path setting
export PATH="./bin:~/bin:$PATH"
PS1='[\h \W$(__git_ps1 " (%s)")]Ω '
