#! /bin/bash

alias vi=vim
alias top='top -o cpu'
alias ctags=/usr/local/bin/ctags
alias rspec=fast_rspec
alias g=git
alias gc='git commit'
alias ga='git add'
alias gst='git status'

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

for i in \
  /opt/homebrew/bin \
  /usr/local/bin \
  ~/.cargo \
  /usr/local/opt/gnu-getopt/bin \
  /usr/local/opt/curl/bin \
  /usr/local/opt/coreutils/libexec/gnubin \
  /usr/local/opt/findutils/libexec/gnubin \
  ~/Library/Android/sdk/tools/bin \
  ~/.bin \
  ~/bin; do
  if [ -d "$i" ]; then
    PATH="$i:$PATH"
  fi
done
export PATH="./bin:$PATH"

# ruby management
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
if [ -d "$HOME/.rbenv" ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  export RBENV_ROOT="$HOME/.rbenv"
  eval "$(rbenv init -)"
fi

# Rails
function rails_command {
  local cmd=$1
  shift
  if [ -e script/rails ]; then
    script/rails $cmd "$@"
  else
    script/$cmd "$@"
  fi
}
alias ss='rails_command server'
alias sc='rails_command console'

if [ -d /Applications/Emacs.app ]; then
  alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs'
fi

if [ -d /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home ]; then
  export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
fi

if [ -d "$HOME/Library/Android/sdk" ]; then
  export ANDROID_HOME=$HOME/Library/Android/sdk
  export PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools
fi

if [ "$BASH_VERSINFO" -ge 4 ]; then
  # bash configurations
  export HISTCONTROL=ignoredups:erasedups
  export HISTSIZE=100000
  export HISTFILESIZE=100000
  export HISTIGNORE="*production*:*swarmsl*"
  shopt -s histappend
  shopt -s autocd
  shopt -s globstar
  shopt -s checkhash

  #readline
  bind 'set completion-ignore-case on'
  bind 'set skip-completed-text on'
  bind 'set show-all-if-ambiguous on'
  bind 'set mark-symlinked-directories on'
  bind 'set mark-directories on'

  # OSX Specific
  if [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
  fi
  export BUNDLER_EDITOR=code
  export LC_CTYPE=en_US

  PS1='[\h \W$(__git_ps1 " (%s)")]Ω '

  if [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
  fi

  if [ -d ~/.bash-completion.d ]; then
    for f in ~/.bash-completion.d/*.{sh,bash}; do source "$f"; done
  fi
fi

if [ -d /usr/local/Cellar/ec2-api-tools/1.7.3.0/libexec ]; then
  export EC2_HOME="/usr/local/Cellar/ec2-api-tools/1.7.3.0/libexec"
fi

# final path setting
alias bc="bc -l"

if [ -x ~/Applications/MPlayer\ OSX\ Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS/mplayer ]; then
  alias mplayer="$HOME/Applications/MPlayer\ OSX\ Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS/mplayer"
fi

if which icalBuddy > /dev/null 2>&1; then
  function today() { iCalBuddy -n -f -nnr " " -ea eventsToday$@ | sed -e "s/\(http[^ \"]*\).*/THEREISALINKHERE\1/g" -e "s/notes:.*THEREISALINKHERE/link: /g" -e "s/THEREISALINKHERE//g"; }
fi
