#!/bin/sh -e

GIT_ROOT=$(git rev-parse --show-toplevel)
COMMAND="$1";
shift || true

if [ -z "$COMMAND" ]; then
  echo "Usage $0 [up|down|test] (run this in the git repo)"
  exit 1
fi

case "$COMMAND" in
  up)
    docker run --rm -v dgraph_gopath:/go -v dgraph_gocache:/root/.cache/go-build -v $GIT_ROOT:/app -w /app/dgraph golang:1.14 go build -o /app/osx-docker-gopath/bin/dgraph
    GOPATH=$GIT_ROOT/osx-docker-gopath docker-compose up "$@";;
  down) GOPATH=$GIT_ROOT/osx-docker-gopath docker-compose -p dgraph down "$@";;
  make) make -C $GIT_ROOT "$@";;
  test) PATH="$GIT_ROOT/dgraph:$PATH" go test "$@";;
esac
