#! /bin/sh

if [ -z "$input" ]; then
  input=avi
fi

if [ "$1" == "--group" ]; then
  if [ "$2" == "--skip" ]; then
    SKIP="$3"
    shift
    shift
  else
    SKIP=0
  fi

  for i in *.$input; do
    if [ $SKIP -gt 0 ]; then 
      SKIP=$((SKIP -1))
      continue
    fi
      "$0" "$i" "$2/`basename "$i" .$input`.mp4"
  done
  exit
fi

INPUT="$1"
shift

ffmpeg -i "$INPUT" -acodec libfaac -ab 160000 -vcodec mpeg4 -b 720kb -mbd 2 -cmp 2 -subcmp 2 -s 640x480 -r 20 "$@"
